### ISSUE TITLE
learn about robot

### ISSUE THREAD

**Issue by Nimingez** [zhanghengsjtu/mobile_manipulator_ros_simulation#1]
Is the description of this type of hybrid robot created by drawing in software and exporting, or is it directly written in xacro? Could you please provide an overview of the general technical process?

**Comment by zhanghengsjtu** [comment]
The xacro should be written by the developers (me in this case). Mesh file (dae or stl format) should be included in the xacro. For simple mesh, you can use predefined shape, a good reference is [here](https://wiki.ros.org/urdf/XML/link) .

 For complex mesh, you have two choices. One is downloaded from other project or search on the internet. For example, the mesh file of the manipulator is from universal robot repo. Another option is drawing the mesh in CAD software, like solidworks, and convert to stl or dae.
